### ISSUE TITLE
cant move

### ISSUE THREAD

**Issue by huang16a** [gabrielSoudry/Fink#1]
<img width="768" alt="screenshot-2020-03-25_16 17 43 35" src="https://user-images.githubusercontent.com/61705585/77515944-6ec82300-6eb4-11ea-9520-e9a93b95a712.png">
what should do?

**Comment by gabrielSoudry** [comment]
It's possible that our servers was down during the night it's now up ! For now it's just a demo application we will work to make it appear on the Play Store !
